### ISSUE TITLE
Can't generate mail addresses: Request failed with status code 401

### ISSUE THREAD

**Issue by mietzen** [dedoussis/icloud-hide-my-email-browser-extension#61] opened 2024-05-18 14:48 UTC
Since a couple of days I can't generate new mail addresses:

```
Error: Request to GET https://p109-maildomainws.icloud.com:443/v2/hme/list failed with status code 401
```

![image](https://github.com/dedoussis/icloud-hide-my-email-browser-extension/assets/31704359/b62b02fe-a4ac-42a0-af15-7331e06dcbe1)

Browser: Firefox 126.0 (64-bit)
macOS: 13.6.6 (22G630) (M1 Pro)

**Comment by dedoussis** [comment] 2024-05-18 15:01
Thanks for reporting this @mietzen! I cannot reproduce on my machine with my personal iCloud account. Would you mind sharing the network logs of the extension? What does the response of `GET /v2/hme/list` look like?

See this guide on how to use the dev tools of firefox on add-ons: https://extensionworkshop.com/documentation/develop/debugging/

Once you open the dev tools on the add-on, try navigating to the `Generate new email` view of pop up and then check the Network tab.

**Comment by dedoussis** [comment] 2024-05-18 15:02
Also, this endpoint is only used for listing existing emails. You should still be able to generate new address if you navigate to the `Generate new email` view of the popup.

**Comment by mietzen** [comment] 2024-05-18 15:17
I tried debugging it, but all request and responses are empty? 

![image](https://github.com/dedoussis/icloud-hide-my-email-browser-extension/assets/31704359/5870ec90-58a7-4823-a9bb-6fda84f54dbc)


Generating give the same error:
`Error: Request to POST https://p109-maildomainws.icloud.com:443/v1/hme/generate failed with status code 401`

**Comment by dedoussis** [comment] 2024-05-18 15:27
@mietzen try disabling the pop-up auto hide from the top-right menu of devtools and retry the requests.

![image](https://github.com/dedoussis/icloud-hide-my-email-browser-extension/assets/24495755/7bab0766-0184-42cb-8172-f93685b8ba7d)

**Comment by mietzen** [comment] 2024-05-18 15:45
That worked 👍  I removed the authentication cookies:

[log.json](https://github.com/dedoussis/icloud-hide-my-email-browser-extension/files/15365909/log.json)

**Comment by dedoussis** [comment] 2024-05-18 16:06
Interesting. Could you try singing out of icloud and signing back in?

**Comment by mietzen** [comment] 2024-05-18 16:08
Already tried, also tried in chromium with the same result

**Comment by mietzen** [comment] 2024-05-27 05:19
Did you push any changes lately? Because it started working again

**Comment by dedoussis** [comment] 2024-10-28 03:47
@mietzen I did not push any changes that might have fixed this. Has this issue come up since your last comment?

**Comment by dedoussis** [comment] 2024-10-28 05:02
Ack, closing the issue.

**Closed by dedoussis** 2024-10-28 05:02 UTC
