### ISSUE TITLE
AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by webepg** [dedoussis/icloud-hide-my-email-browser-extension#38] opened 2023-07-23 09:16 UTC
Hi,

when I try to login I get the 2FA Code, after typing it in the message AxiosError: Request failed with status code 403 appears. No E-Mail Address can be created. Am I doing something wrong?

I'm using Brave Browser

**Comment by Frogy76** [comment] 2023-08-15 08:28
Hi,
I have the same PRoblem with Chrome and Firefox

**Comment by deibertf** [comment] 2023-08-15 09:37
Can confirm, but can still add new emails.
![image](https://github.com/dedoussis/icloud-hide-my-email-browser-extension/assets/24978665/339061b0-e589-4d89-a51a-93c021d3515e)

**Comment by dedoussis** [comment] 2023-08-16 11:42
Hi @webepg! The issue is due to Chromium unexpectedly disabling some static declarative net request rules of the extension. I could not figure out what's the exact root case behind that. It is possible that this could be a bug of Chromium.

Have just pushed a patch to work around this Chromium behaviour. It's been released as version 1.1.2 but awaits a review from the Chrome webstore team.

**Comment by dedoussis** [comment] 2023-08-16 11:45
@Frogy76 and @deibertf, this seems to be another issue unrelated to the above Chromium networking stuff (which is why it's also reproducible in Firefox).

Apple made a change to the base URL of some API of theirs, which broke the extension. Have also fixed that as part of 1.1.2 which should be available in both Firefox and Chrome webstores.

**Closed** 2024-01-28 10:36 UTC
